import NavItem from './NavItem';
import Header from './Header';
import Aside from './Aside';
import SectionTitle from './SectionTitle';
import Chips from './Chips';
import Social from './Social';
import Modal from './Modal';
import ProjectCard from './ProjectCard';
import ProjectInfo from './ProjectInfo';
export {  Aside, NavItem, Header ,SectionTitle,Chips,Social,ProjectInfo ,Modal ,ProjectCard};
